server:
    port: 8761
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
spring:
    application:
        name: eureka-server
    banner:
        location: classpath:banner/banner.txt