
server:
  port: 8083

spring:
  application:
    name: MICROSERVICE-GATEWAY
  banner:
    location: classpath:banner/banner.txt
  cloud:
    gateway:
      routes:
      
        - id: question-service
          uri: lb://MICROSERVICE-QUESTION
          predicates:
            - Path=/question/**

        - id: user-service
          uri: lb://MICROSERVICE-AUTHENTICATION
          predicates:
            - Path=/auth/**

        - id: classroom-service
          uri: lb://MICROSERVICE-CLASSROOMS
          predicates:
            - Path=/classroom/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true